# Generated by Django 3.0.8 on 2020-07-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('timeOfRegistration', models.TimeField(auto_created=True, auto_now=True)),
                ('dateOfRegistration', models.DateField(auto_created=True, auto_now=True)),
                ('enterpriseId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('enterpriseName', models.CharField(max_length=250)),
                ('enterpriseAddress', models.CharField(max_length=250)),
                ('enterpriseEmailAddress', models.EmailField(max_length=250, unique=True)),
                ('enterpriseContactNumber', models.CharField(max_length=10)),
                ('enterpriseGSTNumber', models.CharField(max_length=50, unique=True)),
                ('enterpriseType', models.CharField(max_length=150)),
                ('enterpriseWebsite', models.URLField()),
                ('enterpriseDetails', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenantId', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('tenantName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=250)),
                ('contactNumber', models.CharField(max_length=10, unique=True)),
                ('emailAddress', models.EmailField(max_length=250, unique=True)),
                ('aadhaarNumber', models.CharField(max_length=20, unique=True)),
                ('panNumber', models.CharField(max_length=20, unique=True)),
                ('enterpriseId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('employeeName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=250)),
                ('contactNumber', models.CharField(max_length=10, unique=True)),
                ('emailAddress', models.EmailField(max_length=250, unique=True)),
                ('aadhaarNumber', models.CharField(max_length=20, unique=True)),
                ('panNumber', models.CharField(max_length=20, unique=True)),
                ('enterpriseId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('adminId', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('adminName', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('enterpriseId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Enterprise')),
            ],
        ),
    ]
